services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args: ["APP_PORT=${APP_PORT}"]
    container_name: api
    env_file: [.env]
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports: ["${APP_PORT}:${APP_PORT}"]
    restart: always
    depends_on: [db]
    entrypoint: [ "sh", "-c", "./wait-for-it.sh mysql:3306 -- npx prisma migrate deploy && npm run start" ]
  db:
    image: mysql
    container_name: db
    restart: always
    command: ["mysqld","--mysql_native_password=ON"]
    env_file: [.env]
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    volumes: [mysqldata:/var/lib/mysql]
    ports: ["${DB_PORT}:${DB_PORT}"]
volumes:
  mysqldata:
